import LeftSidebar from "@/components/admin/LeftSidebar";
import "../globals.css"
// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main>
          <LeftSidebar />
          <div className="container mx-auto my-8" style={{ maxWidth: "800px" }}>
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
